import "./CssReset.css";
import "./globals.css";
export const metadata = {
  title: "TugsanYangin",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return <body>{children}</body>;
}
